### ISSUE TITLE
Support for Windows via WinFsp

### ISSUE THREAD

**Issue by acosonic** [miquels/webdavfs#10]
The author of WinFsp might be ready to join efforts if you
decide to support windows via his project

[https://github.com/billziss-gh/winfsp/issues/284](https://github.com/billziss-gh/winfsp/issues/284)

And windows native webdav support is still problematic, regardless of version... 

Also from other various clients, not all work well with webdav, I've managed to 
make only few of them work...

**Comment by miquels** [comment]
I'm not interested in doing any sort of windows development. I have nothing against windows, it's just so very different that it's usually not worth the effort making a low-level project both windows and unix compatible.
