### ISSUE TITLE
"Input/output error" using Nextcloud 13

### ISSUE THREAD

**Issue by gustaebel** [miquels/webdavfs#3]
The server in question is running Nextcloud 13.0.1 on Apache. Mounting with webdavfs works but when I try to write files I get an "Input/output error" (400 Bad Request).

I looked into it and discovered that although Nextcloud uses SabreDAV it apparently does not use its PartialUpdate Plugin which is needed for write support :-( Problematic in my particular case is that webdavfs correctly detects that there is no SabreDAV it can use, but it still sees the apache webserver. Unfortunately the apache has its DAV support deactivated for the files managed by Nextcloud. webdavfs should detect that and fallback to a readonly mount, but it doesn't.

**Comment by miquels** [comment]
Hey, thanks for the report. I think I should probably detect Apache based on the `DAV:` header instead of the `Server:` header. Apache mod_dav sends this:
```
DAV: <http://apache.org/dav/propset/fs/1>
```
I'm assuming nextcloud doesn't send this header, right?

**Comment by gustaebel** [comment]
Nextcloud sends:

    DAV: 1, 3, extended-mkcol

**Comment by miquels** [comment]
I've pushed a fix to master (https://github.com/miquels/webdavfs/commit/c503b3c64070c1fa1e5470711843447a730edc24). Can you check if that resolves the issue?

**Comment by gustaebel** [comment]
Yes, I get "no PUT Range support, writing disabled" when I mount the filesystem. Nevertheless I get a "Permission denied" when I try to write to it, and I can still remove files.

**Comment by miquels** [comment]
Yes, that's correct. Writing to files is disabled, because that is not possible without partial-write support. Meta operations like MKCOL/DELETE etc are not impacted by that, so they still work. Do you have a suggestion for a better warning message?

**Comment by gustaebel** [comment]
I think it would be more intuitive for the filesystem to behave as if it was read-only mounted, in every aspect, e.g. get EROFS when trying to write or delete files. But I think this is a matter of taste. The warning message is fine.

**Comment by miquels** [comment]
What about mounting the filesystem read-only if the server has no partial-write support like you suggested, with a new mount option to override that and enable metadata operation ?

**Comment by gustaebel** [comment]
Yeah, good idea ;-)

**Comment by miquels** [comment]
Fixed in 919a4c96353bb2b2e3a8839c6a47d94598af8ae7 .
