### ISSUE TITLE
undefined: syscall.Dup2 (build failed)

### ISSUE THREAD

**Issue by nephaste** [miquels/webdavfs#7]
Hi i am trying to build webdavfs on Linux with Go 1.10.3

```
export APP=webdavfs
export DIR=/SRC/.MYSCRIPT
export TEMPO=$DIR/tmp1

cd ${TEMPO}
rm -rf *
mkdir -p ${TEMPO}/src
mkdir -p ${TEMPO}/bin
mkdir -p ${TEMPO}/pkg

export GOPATH=${TEMPO}

cd ${TEMPO}/src
mkdir -p github.com/miquels
cd github.com/miquels

git clone https://github.com/miquels/webdavfs

cd webdavfs

go get

GOOS=linux GOARCH=arm64 go build -o ${APP}.arm64 
GOOS=linux GOARCH=arm GOARM=5 go build -o ${APP}.armv5 
GOOS=linux GOARCH=arm GOARM=7 go build -o ${APP}.armv7 
GOOS=linux GOARCH=amd64 go build -o ${APP}.x64 
GOOS=linux GOARCH=386 go build -o ${APP}.i386 
```
result

`root@trusty64:/SRC/.MYSCRIPT/GO# ./WebDAVfs
Cloning into 'webdavfs'...
remote: Enumerating objects: 262, done.
remote: Total 262 (delta 0), reused 0 (delta 0), pack-reused 262
Receiving objects: 100% (262/262), 75.82 KiB | 0 bytes/s, done.
Resolving deltas: 100% (167/167), done.
Checking connectivity... done.
# github.com/miquels/webdavfs
./daemon.go:139:2: undefined: syscall.Dup2
./daemon.go:140:2: undefined: syscall.Dup2
./trace.go:135:2: undefined: syscall.Dup2
./trace.go:136:2: undefined: syscall.Dup2
`

any idea ?

**Comment by miquels** [comment]
what platform is this, i386, x64_64 (aka amd64), arm64 ?

**Comment by nephaste** [comment]
Hi

the goal is to build for Qnap NAS

i386 ---> x86 32bit (intel/amd)
x86_64  --> x86 64bit (intel/amd)
arm64 ---> armv8 

i already used this to build several apps... but first time it fails with this error

**Comment by miquels** [comment]
It looks like arm64 doesn't have the Dup2 syscall. The Dup3 syscall is newer, and has the same + extended functionality, so on that platform dup2(oldfd, newfd) is probably implemented as dup3(oldfd, newfd, 0).

I've added system dependent files to the repo, where Dup2 is implemented by Dup3 on Linux and Dup2 on other platforms. Can you try to pull and rebuild ?

**Comment by nephaste** [comment]
HI Miquels

it works great... i have now my 5 versions for different ARCH

thanks a lot for all... 

will publish it as soon as possible on QnapClub.eu Appcenter for Qnap users community
