### ISSUE TITLE
Nextcloud 15: no PUT Range support

### ISSUE THREAD

**Issue by abishai** [miquels/webdavfs#8]
It looks like SabreDav capabilities are not detected (or broken). I collected a trace, however I found nothing suspicious. Is it working for you ?

**Comment by miquels** [comment]
I made a demo account on nextcloud.com, and did a webdav PROPFIND request:
```
$ curl -i --user "admin:admin" -X OPTIONS https://demo.nextcloud.com/ae8oobah/remote.php/dav/files/admin/
HTTP/1.1 200 OK
Date: Tue, 19 Mar 2019 13:00:23 GMT
Server: Apache
Allow: OPTIONS, GET, HEAD, DELETE, PROPFIND, PUT, PROPPATCH, COPY, MOVE, REPORT
DAV: 1, 3, extended-mkcol, access-control, calendarserver-principal-property-search, nc-calendar-search, nc-enable-birthday-calendar
MS-Author-Via: DAV
```
The [SabreDav PATCH specification](http://sabre.io/dav/http-patch/) says that `sabredav-partialupdate` needs to be advertised in the `DAV:` header. It isn't ... so, file a bug with nextcloud?

**Comment by abishai** [comment]
Good question! I missed that. 
I'll take a look where it returns capabilities.

**Comment by abishai** [comment]
```
Updated: Issue #439. Lots of updates in PATCH support. The Sabre_DAV_PartialUpdate_IFile interface is now deprecated and will be removed in a future version.
```
Looks like Nextcloud uses PATCH method to do partial updates.

**Comment by miquels** [comment]
Well, yes, that *is* the SabreDav standard, to use `PATCH`. In a specific way, see [http://sabre.io/dav/http-patch/](http://sabre.io/dav/http-patch/). However, if a server implements this, it _must_ indicate that by putting `sabredav-partialupdate` in the `DAV:` header reply to an `OPTION` request.

**Comment by miquels** [comment]
If there is no followup to this issue I will close it tomorrow.

**Comment by abishai** [comment]
Yep, it is not activated on Nextcloud side.

**Comment by miquels** [comment]
Let's keep this issue open since the Nextcloud issue is also still open.

**Comment by muety** [comment]
Would it be an option to add a flag that instruct to "forcefully" assume the required feature to be present, even if not advertised?

**Comment by sambler** [comment]
I don't think it is worth opening a new issue, as I am getting the same error with a cpanel webdav setup.

I can add the rwdirops option and skip the "no PUTS range" error, I can then create and delete a dir, but creating or editing a file fails.

I am using FreeBSD 13 and build webdavfs using the newest master revision

```
% curl -i -X OPTIONS https://XXXX.com:2078
HTTP/1.1 200 OK
Date: Tue, 18 Jan 2022 06:43:12 GMT
Server: cPanel
Persistent-Auth: false
Host: XXXX.com:2078
Cache-Control: no-cache, no-store, must-revalidate, private
Connection: Keep-Alive
Vary: Accept-Encoding
Allow: POST, UNLOCK, HEAD, PUT, MOVE, DELETE, PROPPATCH, LOCK, COPY, MKCOL, GET, PROPFIND, OPTIONS
Content-Length: 0
Content-Type: text/plain
Expires: Fri, 01 Jan 1990 00:00:00 GMT
DAV: 1, 2
Keep-Alive: timeout=15, max=96
MS-Author-Via: DAV
```

**Comment by Evidlo** [comment]
Looking through the source code, you can force this to be enabled with the option `-o rwdirops` option.

https://github.com/miquels/webdavfs/blob/117d63347042f65f741b1914ba15c44523503dc2/main.go#L263

**Comment by miquels** [comment]
I've added a mount option "sabredav_partialupdate" to force using the sabredav partialupdate protocol even when the remote server doesn't advertise support for it. See https://github.com/miquels/webdavfs/commit/5751a4455f3d1608635b90e8bb02fd05dc7f0e95
