### ISSUE TITLE
fusefs-webdavfs mounted only readonly

### ISSUE THREAD

**Issue by openkasnet** [miquels/webdavfs#9]
Hello. I added on  **/etc/fstab 
https://disk.example.uz/remote.php/webdav/ /mnt users rw, lite, mountprog=/usr/local/sbin/mount_webdavfs,username=user, password=passwd,-F=/var/tmp/trace.log,-T=webdav,-T=httpreq,-T=httphdr 0 0** 
mounted only readonly
installed package from ports /usr/ports/sysutils/fusefs-webdavfs

OS Type Freebsd 12
⇒  kldstat
Id Refs Address                Size Name
 1   10 0xffffffff80200000  243d390 kernel
 2    1 0xffffffff8263f000    16750 fuse.ko
 3    1 0xffffffff8281a000     2678 intpm.ko
 4    1 0xffffffff8281d000      b10 smbus.ko
 5    1 0xffffffff8281e000     1800 uhid.ko

**Comment by miquels** [comment]
It's probably because your webdav server does not support partial put. If it is nextcloud, see this issue: https://github.com/nextcloud/server/issues/15923

**Comment by openkasnet** [comment]
Yandex Disk is also mounted read only

**Comment by miquels** [comment]
Again, It's probably because your webdav server does not support partial put. Perhaps you can ask Yandex if they can implement it.
